// <auto-generated />
using System;
using BandAPI.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BandAPI.Migrations
{
    [DbContext(typeof(BandAlbumContext))]
    partial class BandAlbumContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BandAPI.Entities.Album", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BandId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(400)")
                        .HasMaxLength(400);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.HasKey("Id");

                    b.HasIndex("BandId");

                    b.ToTable("Albums");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bf3b11e9-ee82-4ccb-8e9e-5efd82652880"),
                            BandId = new Guid("0fe4776c-dfff-4134-aa03-2b7e31558186"),
                            Description = "One of the best albums ever",
                            Title = "Master of Pappets"
                        },
                        new
                        {
                            Id = new Guid("b36c8190-2c9a-4e07-817b-ff767d03e856"),
                            BandId = new Guid("926f664c-930b-49f3-95a0-a4bf241b6c6c"),
                            Description = "Amazing Rock album with a raw sound",
                            Title = "Appetite for Destruction"
                        },
                        new
                        {
                            Id = new Guid("ce41e436-1373-4fdb-9aa3-02759d4a0c63"),
                            BandId = new Guid("3c0da630-dc17-4898-afd4-bbe71f5bb26d"),
                            Description = "Very groovy sound",
                            Title = "Waterloo"
                        },
                        new
                        {
                            Id = new Guid("94c0e8ac-253c-43c7-9ef9-979d1ecb359e"),
                            BandId = new Guid("a024e32a-bda3-404f-8c82-a510a37e67c2"),
                            Description = "Arguably one of the best albums by Oasis",
                            Title = "Be here now"
                        },
                        new
                        {
                            Id = new Guid("c4d67114-ec33-494f-a5fc-c85db4dadd05"),
                            BandId = new Guid("5bdb346e-1f26-41be-a7e3-254a4d2a34f4"),
                            Description = "Awesome debut album by A-ha",
                            Title = "Hunting Hight and Low"
                        });
                });

            modelBuilder.Entity("BandAPI.Entities.Band", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Founded")
                        .HasColumnType("datetime2");

                    b.Property<string>("MainGenre")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("Bands");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0fe4776c-dfff-4134-aa03-2b7e31558186"),
                            Founded = new DateTime(1980, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MainGenre = "Heavy Metall",
                            Name = "Metallica"
                        },
                        new
                        {
                            Id = new Guid("926f664c-930b-49f3-95a0-a4bf241b6c6c"),
                            Founded = new DateTime(1985, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MainGenre = "Rock",
                            Name = "Guns N Roses"
                        },
                        new
                        {
                            Id = new Guid("3c0da630-dc17-4898-afd4-bbe71f5bb26d"),
                            Founded = new DateTime(1965, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MainGenre = "Disco",
                            Name = "ABBA"
                        },
                        new
                        {
                            Id = new Guid("a024e32a-bda3-404f-8c82-a510a37e67c2"),
                            Founded = new DateTime(1991, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MainGenre = "Alternative",
                            Name = "Oasis"
                        },
                        new
                        {
                            Id = new Guid("5bdb346e-1f26-41be-a7e3-254a4d2a34f4"),
                            Founded = new DateTime(1981, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MainGenre = "Pop",
                            Name = "A-ha"
                        });
                });

            modelBuilder.Entity("BandAPI.Entities.Album", b =>
                {
                    b.HasOne("BandAPI.Entities.Band", "Band")
                        .WithMany("Album")
                        .HasForeignKey("BandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
